# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 51f6ef86d5751463047987f6e4d7a800c9aa34ee2711934e2e47f1a7ba05f5dfb5228fa112e4957a6e94a155d6a1ea27ef4da0f66b795dd0f58fa478b2328b9b

test:
  secret_key_base: 72c58ea750bf0ae740273b5972c1661a5b182550567988e5171aecdf6dcaaef34630800dde62e3c3b0f856e7408d9b37dcf50463f436f463d68052369c492daa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
