#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  LD,             sensorQuadEncoder)
#pragma config(Sensor, dgtl11, RD,             sensorQuadEncoder)
#pragma config(Motor,  port2,           DLB,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           DLM,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DLF,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mogoL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mogoR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           DRF,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           DRM,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           DRB,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

void setLDrive(int speed);
void setRDrive(int speed);
void setMogo(int speed);
void drivePID(int dist);
void pre_auton()
{
	SensorValue[LD] = 0;
	SensorValue[RD] = 0;
  bStopTasksBetweenModes = true;
}
task autonomous()
{
		drivePID(2048);

}

task usercontrol()
{

  while (true)
  {
  		if(abs(vexRT[Ch2]) > 15){
  			setLDrive(vexRT[Ch2]);
  		}
  		else{
  		  setLDrive(0);
  		}
  		 if(abs(vexRT[Ch3]) > 15){
  			setRDrive(vexRT[Ch3]);
  		}
  		else{
  		  setRDrive(0);
  		}

  		if(vexRT[Btn6U]){
  			setMogo(127);
  		}
  		else if(vexRT[Btn6D]){
  			setMogo(-127);
  		}
  		else{
  			setMogo(0);
  		}
  		wait1Msec(25);
  }
}

void drivePID(int dist){
	int eL = dist - SensorValue[LD];
	int eR = dist - SensorValue[RD];
	float kP = 0.5;
	int defS = 80;
	int e = eL - eR;
	while(true){
		eL = dist - SensorValue[LD];
		eR = dist - SensorValue[RD];
		e = eL - eR;
		setLDrive(defS + e * kP);
		setRDrive(defS - e * kP);
		if(dist < 10){
			break;
		}

		wait1Msec(25);
	}
}
void turn(int x){
}


void setLDrive(int speed){
	motor[DLB] = speed;
	motor[DLM] = speed;
	motor[DLF] = speed;
}

void setRDrive(int speed){
	motor[DRB] = speed;
	motor[DRM] = speed;
	motor[DRF] = speed;
}
void setMogo(int speed){
	motor[mogoL] = speed;
	motor[mogoR] = speed;
}
